//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birthday.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthdayImage
    {
        public int BirthdayImageID { get; set; }
        public int BirthdayID { get; set; }
        public int FileID { get; set; }
        public int ImageIndex { get; set; }
        public int ImageLeft { get; set; }
        public int ImageTop { get; set; }
        public int ImageWidth { get; set; }
    
        public virtual File File { get; set; }
        public virtual Birthday Birthday { get; set; }
    }
}
