//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birthday.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birthday
    {
        public Birthday()
        {
            this.Congratulations = new HashSet<Congratulation>();
            this.BirthdayImages = new HashSet<BirthdayImage>();
        }
    
        public int BirthdayID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string Html { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public bool Published { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> Age { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string FacebookUrl { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Template Template { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Congratulation> Congratulations { get; set; }
        public virtual ICollection<BirthdayImage> BirthdayImages { get; set; }
    }
}
