//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birthday.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BirthdayContext : DbContext
    {
        public BirthdayContext()
            : base("name=BirthdayContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Congratulation> Congratulations { get; set; }
        public DbSet<CongratulationType> CongratulationTypes { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<Gender> Genders { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Birthday> Birthdays { get; set; }
        public DbSet<TemplateImage> TemplateImages { get; set; }
        public DbSet<BirthdayImage> BirthdayImages { get; set; }
        public DbSet<BirthdayText> BirthdayTexts { get; set; }
    }
}
