//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birthday.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.BirthdayImages = new HashSet<BirthdayImage>();
        }
    
        public int FileID { get; set; }
        public string Name { get; set; }
        public byte[] Content { get; set; }
        public string MimeType { get; set; }
        public int ContentLength { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserID { get; set; }
    
        public virtual ICollection<BirthdayImage> BirthdayImages { get; set; }
        public virtual User User { get; set; }
    }
}
