//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birthday.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender
    {
        public Gender()
        {
            this.Birthdays = new HashSet<Birthday>();
        }
    
        public int GenderID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Birthday> Birthdays { get; set; }
    }
}
