//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Birthday.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateImage
    {
        public int TemplateImageID { get; set; }
        public int TemplateID { get; set; }
        public int ImageIndex { get; set; }
        public int ImageLeft { get; set; }
        public int ImageTop { get; set; }
        public int ImageWidth { get; set; }
        public int ImageHeight { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
